language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - hhvm
  - 5.4
  - 5.3

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - composer update $PREFER_LOWEST

script: ./bin/phpunit
