language: php

jobs:
  include:
    - php: 5.3
      dist: precise

    - php: 5.4
      dist: trusty

    - php: 5.4
      dist: trusty

    - php: 5.5
      dist: trusty

    - php: 5.6
      dist: trusty

    - php: 7.0
      dist: trusty

    - php: 7.1
      dist: trusty

    # - { php: 7.2, dist: trusty }
    # - { php: 7.3, dist: trusty }

    - hhvm-3.3
      dist: trusty

env:
  matrix:
    # - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
  - composer update $PREFER_LOWEST

script: ./bin/phpunit
